/**
 * 翻译字典
 * safeGlobalDict: 安全长句，可在引号内全局替换
 * riskyShortWords: 危险短词，仅在 UI 属性上下文中替换
 */

const safeGlobalDict = {
  // ── Glass 主页 ──
  'New Agent': '新建智能体',
  'New Agents Window (Glass)': '新建智能体窗口 (Glass)',
  'New Agent in Project': '在项目中新建智能体',
  'New Agent with Context': '带上下文新建智能体',
  'New Agent with Model': '指定模型新建智能体',
  'New Agent with Query': '带查询新建智能体',
  'New Agent (preserve editor panel)': '新建智能体（保留编辑器面板）',
  'Build in New Agent': '在新智能体中构建',
  'Automations': '自动化',
  'Automate repetitive tasks with always-on cloud agents that respond to environment triggers.':
    '使用始终在线的云智能体自动执行重复性任务，响应环境触发器。',
  "Automate repetitive tasks with always-on agents and configure Cursor's built-in agents for your team.":
    '使用始终在线的智能体自动执行重复性任务，并为你的团队配置 Cursor 内置智能体。',
  'Customize': '自定义',
  'Pinned': '已固定',
  'Repositories': '仓库',
  'Plan New Idea': '规划新想法',
  'Multitask': '多任务',
  'Multitask Mode': '多任务模式',
  'Editor Window': '编辑器窗口',
  'Refer friends, earn up to $250': '推荐好友，最高赚取 $250',
  'Drag and drop agent chats to split your view into tiled panes':
    '拖放智能体聊天，将视图拆分为平铺窗格',
  'Plan, search, make edits, run commands': '规划、搜索、编辑、运行命令',
  'Plan and design before coding...': '编码前先规划与设计…',
  'Plan, Build, / for skills, @ for context': '规划、构建，/ 调用技能，@ 添加上下文',
  'Build in Cloud': '在云端构建',
  'Build Locally': '本地构建',
  'Build in Parallel': '并行构建',
  'Building...': '构建中…',
  'Home MCP Servers': '主页 MCP 服务器',
  'Local Only': '仅本地',
  'Local folder': '本地文件夹',

  // ── Settings 导航与 General ──
  'Cursor Account': 'Cursor 账号',
  'Manage Account': '管理账号',
  'Manage your account and billing': '管理您的账号与账单',
  'Pull Requests': '拉取请求',
  'Review Provider': '审查提供商',
  'Choose GitHub or Graphite for pull request links on web and desktop.':
    '选择 GitHub 或 Graphite 作为网页和桌面端拉取请求链接提供方。',
  'PR Link Destination': 'PR 链接打开方式',
  'Open pull request links inside Cursor or in the default browser.':
    '在 Cursor 内或默认浏览器中打开拉取请求链接。',
  'Open pull request links inside Cursor or the default browser':
    '在 Cursor 内或默认浏览器中打开拉取请求链接',
  'Inside Cursor': '在 Cursor 内',
  'Warning Notifications': '警告通知',
  'Show warning-level in-app toasts.': '显示应用内警告级别提示。',
  'Menu Bar Icon': '菜单栏图标',
  'Show Cursor in menu bar.': '在菜单栏显示 Cursor。',
  'Appearance': '外观',
  'Plan & Usage': '套餐与用量',
  'Worktrees': '工作树',
  'Indexing': '索引',
  'Invite Team Members': '邀请团队成员',
  'Accelerate development, shared knowledge, and context across your team':
    '跨团队加速开发并共享知识与上下文',
  'Preferences': '偏好设置',
  'Sync layouts across windows': '跨窗口同步布局',
  'When enabled, all windows share the same layout': '启用后，所有窗口共享相同布局',
  'Editor Settings': '编辑器设置',
  'Configure font, formatting, minimap and more': '配置字体、格式化、缩略图等',
  'Keyboard Shortcuts': '键盘快捷键',
  'Configure keyboard shortcuts': '配置键盘快捷键',
  'Import Settings from VS Code': '从 VS Code 导入设置',
  'Import settings, extensions, and keybindings from VS Code':
    '导入 VS Code 的设置、扩展和快捷键绑定',
  'See warnings and tips that you\'ve hidden': '查看您已隐藏的警告和提示',
  "See warnings and tips that you've hidden": '查看您已隐藏的警告和提示',
  'Layout': '布局',
  'Status Bar': '状态栏',
  'Show status bar': '显示状态栏',
  'Auto-hide editor when empty': '空闲时自动隐藏编辑器',
  'When all editors are closed, hide the editor area and maximize chat':
    '关闭所有编辑器时，隐藏编辑器并最大化聊天窗口',
  'Notifications': '通知',
  'System Notifications': '系统通知',
  'Show system notifications when Agent completes or needs attention':
    '智能体完成任务或需要注意时显示系统通知',
  'System Tray Icon': '系统托盘图标',
  'Show Cursor in system tray': '在系统托盘显示 Cursor',
  'Completion Sound': '完成提示音',
  'Play a sound when Agent finishes responding': '智能体完成响应时播放提示音',
  'Privacy': '隐私',
  'Rules, Skills, Subagents': '规则、技能与子智能体',
  'Tools & MCP': '工具与 MCP',
  'Indexing & Docs': '索引与文档',
  'Cloud Agents': '云端智能体',
  'Team Plan': '团队版',
  'Plugins': '插件',
  'Search settings': '搜索设置',
  'Search Settings': '搜索设置',

  // ── Agents 设置 ──
  'Auto-Run Mode': '自动运行模式',
  'Choose how Agent runs tools like command execution, MCP, and file writes.':
    '选择智能体如何运行命令执行、MCP 和文件写入等工具。',
  'Command Allowlist': '命令白名单',
  'Commands that can run automatically': '可自动运行的命令',
  'MCP Allowlist': 'MCP 白名单',
  'MCP tools that can run automatically. Format: \'server:tool\', \'server:*\' for all tools from a server, \'*:tool\' for a tool from any server, or *:* for all tools from all servers':
    '可自动运行的 MCP 工具。格式：\'server:tool\'、\'server:*\' 表示某服务器全部工具、\'*:tool\' 表示任意服务器的某工具、*:* 表示所有工具',
  'Fetch Domain Allowlist': '请求域名白名单',
  'Domains that Agent can fetch from automatically. Use \'*\' for all domains, \'*.example.com\' for wildcard subdomains.':
    '智能体可自动请求的域名。使用 \'*\' 匹配所有域名，\'*.example.com\' 匹配通配符子域名。',
  'Auto-Approved Mode Transitions': '自动批准的模式切换',
  'Mode transitions that will be automatically approved without prompting.':
    '无需提示即自动批准的模式切换。',
  'Browser Protection': '浏览器保护',
  'Prevent Agent from automatically running Browser tools': '阻止智能体自动运行浏览器工具',
  'MCP Tools Protection': 'MCP 工具保护',
  'Prevent Agent from automatically running MCP tools': '阻止智能体自动运行 MCP 工具',
  'File-Deletion Protection': '文件删除保护',
  'Prevent Agent from deleting files automatically': '阻止智能体自动删除文件',
  'External-File Protection': '外部文件保护',
  'Prevent Agent from creating or modifying files outside of the workspace automatically':
    '阻止智能体自动创建或修改工作区外的文件',
  'Default Location': '默认位置',
  'Where to open new agents': '新智能体的打开位置',
  'Text Size': '文字大小',
  'Adjust the conversation text size': '调整对话文字大小',
  'Ask Every Time': '每次询问',
  'Use Allowlist': '使用白名单',
  'Run Everything': '运行所有',
  'Settings': '设置',
  'Extra Large': '超大',
  'Cursor Tab': 'Cursor Tab 补全',
  'Context-aware, multi-line suggestions around your cursor based on recent edits':
    '基于最近编辑，在光标周围提供上下文感知的多行建议',
  'Partial Accepts': '部分接受',
  'Accept the next word of a suggestion via Ctrl+RightArrow':
    '通过 Ctrl+右箭头接受建议的下一个单词',
  'Suggestions While Commenting': '注释时建议',
  'Allow Tab to trigger while in a comment region': '允许在注释区域中触发 Tab 补全',
  'Whitespace-Only Suggestions': '仅空白建议',
  'Suggest edits like new lines and indentation that modify whitespace only':
    '仅建议修改空白的编辑，如换行和缩进',
  'Automatically import necessary modules for TypeScript': '自动为 TypeScript 导入必要的模块',
  'Auto Import for Python': 'Python 自动导入',
  'Enable auto import for Python. This is a beta feature.': '启用 Python 自动导入。这是一个测试功能。',
  'Provide domain-specific knowledge and workflows for the agent':
    '为智能体提供特定领域的知识和工作流',
  'Include third-party Plugins, Skills, and other configs': '包含第三方插件、技能和其他配置',
  'Automatically import agent configs from other tools': '自动从其他工具导入智能体配置',
  'Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.':
    '使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。',
  'Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.':
    '技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。',
  'No Skills Yet': '暂无技能',
  'Skills help the agent accomplish specific tasks': '技能帮助智能体完成特定任务',
  'New Skill': '新建技能',
  'Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.':
    '创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。',
  'No Subagents Yet': '暂无子智能体',
  'Create specialized agents to handle focused tasks': '创建专业智能体来处理专项任务',
  'New Subagent': '新建子智能体',
  'Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.':
    '创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。',
  'No Commands Yet': '暂无命令',
  'Create commands to build reusable workflows': '创建命令以构建可复用工作流',
  'New Command': '新建命令',
  '+ New': '+ 新建',
  'Auto-Clear Chat': '自动清除聊天',
  'After periods of inactivity, open the Agent Pane to a new conversation':
    '一段时间不活动后，将智能体面板打开为新对话',
  'Submit with Ctrl + Enter': '使用 Ctrl + Enter 提交',
  'When enabled, Ctrl + Enter submits chat and Enter inserts a newline':
    '启用后，Ctrl + Enter 提交聊天，Enter 插入换行',
  'Max Tab Count': '最大标签页数',
  'Limit how many chat tabs can be open at once': '限制同时打开的聊天标签页数量',
  'Queue Messages': '消息队列',
  'Adjust the default behavior of sending a message while Agent is running':
    '调整智能体运行时发送消息的默认行为',
  'Send after current message': '当前消息后发送',
  'Stop & send right away': '立即停止并发送',
  'Usage Summary': '用量摘要',
  'When to show the usage summary at the bottom of the chat pane':
    '何时在聊天面板底部显示用量摘要',
  'Agent Autocomplete': '智能体自动补全',
  'Contextual suggestions while prompting Agent': '向智能体提问时提供上下文建议',

  // ── Agent Review ──
  'Start Agent Review on Commit': '代码提交时启动智能体审查',
  'Automatically review your changes for issues after each commit':
    '在每次提交后自动审查您的更改是否存在问题',
  'Include Submodules in Agent Review': '在智能体审查中包含子模块',
  'Include changes from Git submodules in the review': '在审查中包含 Git 子模块的更改',
  'Include Untracked Files in Agent Review': '在智能体审查中包含未跟踪文件',
  'Include untracked files (new files not yet added to Git) in the review':
    '在审查中包含未跟踪文件（尚未添加到 Git 的新文件）',
  'Default Approach': '默认方式',
  'Choose between quick or more thorough, higher-cost analysis':
    '选择快速或更彻底、成本更高的分析',

  // ── Context & Tools ──
  'Web Search Tool': '网络搜索工具',
  'Allow Agent to search the web for relevant information': '允许智能体在网络上搜索相关信息',
  'Auto-Accept Web Search': '自动接受网络搜索',
  'Skip approval dialog; Agent may run web searches automatically':
    '跳过批准对话；智能体可自动运行网络搜索',
  'Web Fetch Tool': '网页获取工具',
  'Allow Agent to fetch content from URLs': '允许智能体从 URL 获取内容',
  'Hierarchical Cursor Ignore': '分层 Cursor 忽略',
  'Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.':
    '将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。',
  'Ignore Symlinks in Cursor Ignore Search': '在 Cursor 忽略搜索中忽略符号链接',
  'Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.':
    '请谨慎使用。在查找 .cursorignore 文件时跳过符号链接。仅当代码库包含大量符号链接且均可直接访问时才启用。更改此设置需重启 Cursor。',
  'Applying Changes': '应用更改',
  'Inline Diffs': '内联差异',
  'Show inline diff decorations in the editor instead of only showing changes in the review panel':
    '在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改',
  'Jump to Next Diff on Accept': '接受时跳转到下一个差异',
  'Automatically jump to the next diff when accepting changes with Ctrl+Y':
    '使用 Ctrl+Y 接受更改时自动跳转到下一个差异',
  'Auto Format on Agent Finish': '智能体完成时自动格式化',
  'Automatically format files when the agent finishes': '智能体完成任务时自动格式化文件',
  'Inline Editing & Terminal': '内联编辑与终端',
  'Legacy Terminal Tool': '旧版终端工具',
  'Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations':
    '在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统',
  'Toolbar on Selection': '选中时显示工具栏',
  'Show Add to Chat & Quick Edit buttons when selecting code':
    '选择代码时显示「添加到聊天」和「快速编辑」按钮',
  'Auto-Parse Links': '自动解析链接',
  'Automatically parse links when pasted into Quick Edit (Ctrl+K) input':
    '粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接',
  'Themed Diff Backgrounds': '主题差异背景',
  'Use themed background colors for inline code diffs': '为内联代码差异使用主题背景色',
  'Terminal Hint': '终端提示',
  'Show a hint for Ctrl+K in the Terminal': '在终端中显示 Ctrl+K 提示',
  'Preview Box for Terminal Ctrl+K': '终端 Ctrl+K 的预览框',
  'Use a preview box instead of streaming responses directly into the shell':
    '使用预览框而不是将响应直接流式传输到 shell 中',
  'Collapse Auto-Run Commands': '折叠自动运行命令',
  'Collapse auto-run command output by default in Terminal command previews':
    '在终端命令预览中默认折叠自动运行的命令输出',
  'Voice Mode': '语音模式',
  'Submit Keywords': '提交关键字',
  'Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.':
    '在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。',
  'Attribution': '代码署名',
  'Commit Attribution': '提交署名',
  'Mark Agent commits as \'Made with Cursor\'': '将智能体提交标记为「Made with Cursor」',
  'PR Attribution': 'PR 署名',
  'Mark pull requests as made with Cursor': '将拉取请求标记为使用 Cursor 制作',
  'Privacy Mode': '隐私模式',
  'Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.':
    '您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。',
  'Data Sharing is controlled by the team admin. Configure here.':
    '数据共享由团队管理员控制。在此配置。',

  // ── Codebase / Indexing ──
  'Codebase': '代码库',
  'Codebase Indexing': '代码库索引',
  'Delete Index': '删除索引',
  'Index New Folders': '索引新文件夹',
  'Automatically index any new folders with fewer than 250,000 files':
    '自动索引少于 250,000 个文件的新文件夹',
  'View included files.': '查看已包含的文件。',
  'Team-Level Repository Control': '团队级代码库控制',
  'Disable AI features in specific repositories based on file pattern':
    '基于文件匹配模式在特定代码库中禁用 AI 功能',
  'Index Repositories for Instant Grep': '为 Instant Grep 索引代码库',
  'Automatically index repositories to speed up Grep searches. All data is stored locally.':
    '自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。',
  'Crawl and index custom resources and developer docs': '爬取并索引自定义资源和开发者文档',
  'No Docs Added': '未添加文档',
  'Add Doc': '添加文档',
  'Increase limits for faster responses': '提升额度以获取更快响应',
  'Ignore Files in .cursorignore': '忽略 .cursorignore 中的文件',
  'Learn about codebase indexing': '了解代码库索引',
  'Agent Review': '智能体审查',

  // ── Cloud / Network / Beta ──
  'Get Started': '开始使用',
  'Cloud Agents require a Git repository in an open folder.':
    '云智能体需要打开的文件夹中包含 Git 仓库。',
  'Open a Git repository': '打开 Git 仓库',
  'Background agents only work in folders with a git repository.':
    '后台智能体仅在包含 git 仓库的文件夹中工作。',
  'Please open a folder that contains a git repository to use this feature.':
    '请打开包含 git 仓库的文件夹以使用此功能。',
  'Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs':
    '使用技能、规则、智能体、钩子和 MCP 扩展 Cursor',
  'HTTP Compatibility Mode': 'HTTP 兼容模式',
  'HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.':
    '推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。',
  'Required Domains': '必需的域名',
  'These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.':
    '必须可访问这些域名，Cursor 才能正常工作。请将它们添加到防火墙或代理白名单中。',
  'Network Diagnostics': '网络诊断',
  'Check network connectivity to all Cursor services': '检查与所有 Cursor 服务的网络连接',
  'Update Access': '更新通道',
  'By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.':
    '默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。',
  'Extension RPC Tracer': '扩展 RPC 追踪器',
  'Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.':
    '将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。',
  'Hooks let you run custom scripts at specific points during the agent\'s execution to modify behavior, enforce policies, or add custom logging.':
    '钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。',
  'No hooks configured': '未配置钩子',
  'No hook executions yet': '暂无钩子执行记录',
  'Browser Automation': '浏览器自动化',
  'Browser automation disabled': '浏览器自动化已禁用',
  'Show Localhost Links in Browser': '在浏览器中显示 Localhost 链接',
  'Automatically open localhost links in the Browser Tab':
    '自动在浏览器标签页中打开 localhost 链接',
  'Learn about Rules': '了解规则',
  'Learn about Skills': '了解技能',
  'Learn about Subagents': '了解子智能体',
  'Learn about Commands': '了解命令',
  'User Rule': '用户规则',
  'Project Rule': '项目规则',
  'Add from GitHub/GitLab': '从 GitHub/GitLab 添加',
  'Project Command': '项目命令',
  'User Command': '用户命令',
  'New MCP Server': '新建 MCP 服务器',
  'Add a Custom MCP Server': '添加自定义 MCP 服务器',
  'Balanced quality and speed, recommended for most tasks':
    '平衡质量和速度，推荐用于大多数任务',
  'Multiple models require a Git repository.': '使用多模型功能需要 Git 仓库。',
  'Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.':
    '确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。',
  'Reset "Don\'t Ask Again" Dialogs': '重置「不再询问」弹窗',
  'No Hidden Dialogs Yet': '暂无隐藏的弹窗',
  'You haven\'t marked any dialogs as "Don\'t ask again". Any hidden dialogs will appear here to manage.':
    '您尚未将任何弹窗标记为「不再询问」。任何隐藏的弹窗都将显示在此处以供管理。',
  'Copy Domains': '复制域名',
  'Run Diagnostic': '运行诊断',
  'Nightly Updates Apply Automatically': '每夜更新自动应用',
  'Nightly builds will silently download and install updates without prompting you.':
    '每夜版本将静默下载并安装更新，不会提示您。',

  // ── Agent 聊天与操作 ──
  'Add Agent': '添加智能体',
  'Abort Agent and Restore Query': '中止智能体并恢复查询',
  'Abort Chat': '中止聊天',
  'Accept All': '全部接受',
  'Accept Edits': '接受编辑',
  'Accept Mode Switch': '接受模式切换',
  'Accept Partial Edit': '接受部分编辑',
  'Accept Suggestion': '接受建议',
  'Accept & Run': '接受并运行',
  'Reject All': '全部拒绝',
  'Reject Edits': '拒绝编辑',
  'Stop': '停止',
  'Send': '发送',
  'Submit': '提交',
  'Thinking...': '思考中…',
  'Running...': '运行中…',
  'Generating...': '生成中…',
  'Waiting for approval': '等待批准',
  'Action Needed': '需要操作',
  'Add to Chat': '添加到聊天',
  'Quick Edit': '快速编辑',
  'New Chat': '新聊天',
  'Cancel Chat': '取消聊天',
  'Clear Chat': '清空聊天',
  'Copy Message': '复制消息',
  'Regenerate': '重新生成',
  'Retry': '重试',
  'Undo All': '全部撤销',
  'Apply All': '全部应用',
  'Review Changes': '审查更改',
  'View Diff': '查看差异',
  'Open in Editor': '在编辑器中打开',
  'Run Command': '运行命令',
  'Run Terminal Command': '运行终端命令',
  'Approve': '批准',
  'Deny': '拒绝',
  'Skip': '跳过',
  'Allow Once': '允许一次',
  'Always Allow': '始终允许',
  'Plan Mode': '规划模式',
  'Agent Mode': '智能体模式',
  'Ask Mode': '提问模式',
  'Debug Mode': '调试模式',
  'Switch to Agent': '切换到智能体',
  'Switch to Ask': '切换到提问',
  'Switch to Plan': '切换到规划',
  'No results found': '未找到结果',
  'No results found.': '未找到结果。',
  'Type to search': '输入以搜索',
  'Type to filter': '输入以筛选',
  'Close': '关闭',
  'More Actions...': '更多操作…',
  'More Actions': '更多操作',
  'Loading...': '加载中…',
  'Saving...': '保存中…',
  'Saved': '已保存',
  'Failed': '失败',
  'Success': '成功',
  'Error': '错误',
  'Warning': '警告',
  'Info': '信息',
  'OK': '确定',
  'Done': '完成',
  'Continue': '继续',
  'Back': '返回',
  'Next': '下一步',
  'Previous': '上一步',
  'Learn more': '了解更多',
  'Documentation': '文档',
  'About Cursor': '关于 Cursor',
  'Log Out': '退出登录',
  'Sign In': '登录',
  'Sign Up': '注册',
  'Upgrade': '升级',
  'Manage Subscription': '管理订阅',
  'Pro Plan': 'Pro 套餐',
  'Free Plan': '免费套餐',
  'Business Plan': '商业版',
  'Team Plan': '团队版',
  'Open Folder': '打开文件夹',
  'Open File': '打开文件',
  'Browse Marketplace': '浏览插件市场',
  'Installed MCP Servers': '已安装的 MCP 服务器',
  'Add MCP Server': '添加 MCP 服务器',
  'Add MCP': '添加 MCP',
  'Configure MCP': '配置 MCP',
  'No MCP servers configured': '未配置 MCP 服务器',
  'Suggested': '推荐',
  'Recommended': '推荐',
  'Enabled': '已启用',
  'Disabled': '已禁用',
  'Configure': '配置',
  'Reset': '重置',
  'Restore Defaults': '恢复默认',
  'Export': '导出',
  'Import': '导入',
  'Delete': '删除',
  'Remove': '移除',
  'Rename': '重命名',
  'Duplicate': '复制',
  'Copy Link': '复制链接',
  'Share': '分享',
  'Copy': '复制',
  'Paste': '粘贴',
  'Cut': '剪切',
  'Select All': '全选',
  'Find': '查找',
  'Replace': '替换',
  'Refresh': '刷新',
  'Reload': '重新加载',
  'Restart': '重启',
  'Install': '安装',
  'Uninstall': '卸载',
  'Update': '更新',
  'Check for Updates': '检查更新',
  'Downloading update...': '正在下载更新…',
  'Update available': '有可用更新',
  'Up to date': '已是最新',

  // ── 自检补全：Settings 侧栏与描述（无句号变体）──
  'Profile': '账号',
  'VS Code Settings': 'VS Code 设置',
  'Developer': '开发者',
  'Self-driving PRs': '自动 PR',
  'Contact': '联系我们',
  'Show warning-level in-app toasts': '显示应用内警告级别提示',
  'Show Cursor in menu bar': '在菜单栏显示 Cursor',
  'Open pull request links inside Cursor or in the default browser':
    '在 Cursor 内或默认浏览器中打开拉取请求链接',
  'Show warning-level in-app notifications in Glass mode. Errors and informational notifications are always shown.':
    '在 Glass 模式下显示应用内警告级别通知。错误和信息类通知始终显示。',
  'Default Browser': '默认浏览器',
  'Automate with Hooks': '使用 Hooks 自动化',

  // ── Agent 聊天与操作（补全）──
  'Learn More': '了解更多',
  'Learn More...': '了解更多…',
  'Open Settings': '打开设置',
  'Open Settings (UI)': '打开设置 (UI)',
  'Open Settings (JSON)': '打开设置 (JSON)',
  'Open User Settings (JSON)': '打开用户设置 (JSON)',
  'Dismiss': '忽略',
  'No results': '无结果',
  'Start New Chat': '开始新聊天',
  'Fork Chat': '分叉聊天',
  'View Plan': '查看规划',
  'Needs Attention': '需要关注',
  'Stop generation': '停止生成',
  'Search models': '搜索模型',
  'Add Models': '添加模型',
  'Max Mode': 'Max 模式',
  'Allowlist': '白名单',
  'Share Data': '共享数据',
  'Data Sharing': '数据共享',
  'Copy Request ID': '复制请求 ID',
  'Reload Window': '重新加载窗口',
  'Create PR': '创建 PR',
  'Continue Anyway': '仍然继续',
  'Move to Local': '移至本地',
  'Add to Home': '添加到主页',
  'Open as Editor': '在编辑器中打开',
  'Recent': '最近',
  'Archived': '已归档',
  'Manage': '管理',
  'Team': '团队',
  'Cloud': '云端',
  'Loading': '加载中',
  'Less': '收起',
  'Search or Paste Link': '搜索或粘贴链接',
  'Thinking': '思考中',
  'Planning': '规划中',
  'Building': '构建中',
  'Reviewing': '审查中',
  'Merge Editor': '合并编辑器',
  'Stash changes': '暂存更改',
  'Checkout Branch': '切换分支',
  'Open Workspace': '打开工作区',
  'Authenticate': '认证',
  'Environment': '环境',
  'Installed': '已安装',
  'Preview': '预览',
  'Scope': '范围',
  'Source': '来源',
  'Changes': '更改',
  'Commit': '提交',
  'Workspace': '工作区',
  'Description': '描述',
  'Name': '名称',
  'Type': '类型',
  'Status': '状态',
  'Weight': '权重',
  'Author': '作者',
  'Editor': '编辑器',
  'Restore': '恢复',
  'Review': '审查',
  'Clear': '清空',
  'Enable': '启用',
  'Merge': '合并',
  'Command': '命令',
  'Browse MCPs': '浏览 MCP',
  'Add to Project': '添加到项目',
  'Connection Failed': '连接失败',
  'Copy link': '复制链接',
  'Delete Rule': '删除规则',
  'Export Transcript': '导出对话记录',
  'Open New Agent Chat': '打开新智能体聊天',
  'Parallelize Build with Multitask Mode.': '使用多任务模式并行构建。',
  'Search Agents': '搜索智能体',
  'Pinned conversations': '已固定对话',
  'Voice input': '语音输入',
  'Attach images': '附加图片',
  'Submit message': '提交消息',
  'Queue message': '排队消息',
  'Waiting for your response': '等待您的回复',
  'Run in sandbox': '在沙箱中运行',
  'Web Search': '网络搜索',
  'Tools & MCPs': '工具与 MCP',
  'Indexing & Docs': '索引与文档',

  // ── Settings 页面补全 ──
  'Default Model': '默认模型',
  'New Messages': '新消息',
  'Manually Sent Messages from Queue': '从队列手动发送的消息',
  'Give the Agent a Confetti Cannon': '给智能体一个礼花炮',
  'Allow the agent to celebrate with a shower of confetti':
    '允许智能体用礼花庆祝',
  'Window Restoration': '窗口恢复',
  'Continue Interrupted Agents': '继续中断的智能体',
  'Profile Image': '头像',
  'First Name': '名',
  'Last Name': '姓',
  'Handle': '用户名',
  'Links': '链接',
  'Link 1': '链接 1',
  'Social and website links on the public profile page':
    '公开资料页上的社交和网站链接',

  // ── 设置页补全（v1.2.1）──
  'Code Intelligence': '代码智能',
  'Follow System High Contrast': '跟随系统高对比度',
  'Switch to a high contrast theme when your OS is in a high contrast mode':
    '当系统处于高对比度模式时切换到高对比度主题',
  'Voice Submit Keywords': '语音提交关键字',
  'Custom words that submit a voice prompt. Spaces and punctuation are ignored.':
    '提交语音指令的自定义关键词。空格和标点会被忽略。',
  'Context and Tools': '上下文与工具',
  'Open Local Links in Cursor Browser': '在 Cursor 浏览器中打开本地链接',
  'Open Web Links in Cursor Browser': '在 Cursor 浏览器中打开网页链接',
};

const riskyShortWords = {
  General: '通用',
  Agents: '智能体',
  Tab: 'Tab 补全',
  Models: '模型',
  Plugins: '插件',
  Hooks: '钩子',
  Network: '网络',
  Beta: '测试功能',
  Marketplace: '插件市场',
  Docs: '官方文档',
  Open: '打开',
  Invite: '邀请',
  Import: '导入',
  Show: '显示',
  'Auto-Run': '自动运行',
  Pane: '面板',
  Small: '小',
  Default: '默认',
  Large: '大',
  Imports: '导入',
  Rules: '规则',
  Skills: '技能',
  Subagents: '子智能体',
  Commands: '命令',
  Unlimited: '无限制',
  Custom: '自定义',
  Auto: '自动',
  Always: '始终',
  Never: '从不',
  Quick: '快速',
  Deep: '深度',
  Context: '上下文',
  'Log Out': '退出登录',
  'Open Folder': '打开文件夹',
  'Browse Marketplace': '浏览插件市场',
  Suggested: '推荐',
  Development: '开发',
  'Early Access': '抢先体验',
  Nightly: '每夜版',
  'Configured Hooks': '已配置的钩子',
  'Execution Log': '执行日志',
  'Clear log': '清空日志',
  Tools: '工具',
  Browser: '浏览器',
  Off: '关闭',
  'Browser Tab': '浏览器标签页',
  Cancel: '取消',
  Confirm: '确认',
  Hide: '隐藏',
  Edit: '编辑',
  Home: '主页',
  Local: '本地',
  Search: '搜索',
  More: '更多',
  Build: '构建',
  Plan: '规划',
  Accept: '接受',
  Reject: '拒绝',
  Agent: '智能体',
  Chat: '聊天',
  Ask: '提问',
  Add: '添加',
  New: '新建',
  Save: '保存',
  Apply: '应用',
  Undo: '撤销',
  Redo: '重做',
  Yes: '是',
  No: '否',
  On: '开',
  Off: '关',
  All: '全部',
  None: '无',
  File: '文件',
  Files: '文件',
  Folder: '文件夹',
  Terminal: '终端',
  Output: '输出',
  Debug: '调试',
  Run: '运行',
  Stop: '停止',
  Pause: '暂停',
  Resume: '继续',
  Start: '开始',
  End: '结束',
  Help: '帮助',
  About: '关于',
  Preferences: '偏好设置',
  Appearance: '外观',
  Indexing: '索引',
  Privacy: '隐私',
  Notifications: '通知',
};

const { automationsDict } = require('./dict-automations');
const { appearanceDict } = require('./dict-appearance');
const { settingsPagesDict } = require('./dict-settings-pages');
Object.assign(safeGlobalDict, automationsDict, appearanceDict, settingsPagesDict);

module.exports = { safeGlobalDict, riskyShortWords };
